/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#131317',
        'surface-dim': '#131317',
        'surface-bright': '#39393d',
        'surface-container-lowest': '#0e0e12',
        'surface-container-low': '#1b1b1f',
        'surface-container': '#1f1f23',
        'surface-container-high': '#2a292e',
        'surface-container-highest': '#353439',
        'on-surface': '#e4e1e7',
        'on-surface-variant': '#b9cacb',
        'outline': '#849495',
        'outline-variant': '#3b494b',
        'surface-tint': '#00dbe9',
        'primary': '#dbfcff',
        'on-primary': '#00363a',
        'primary-container': '#00f0ff',
        'on-primary-container': '#006970',
        'primary-fixed-dim': '#00dbe9',
        'secondary': '#ffdb9d',
        'secondary-container': '#feb700',
        'tertiary': '#fff3f2',
        'tertiary-container': '#ffcec8',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'background': '#131317',
        'on-background': '#e4e1e7',
        'neon-cyan': '#00F0FF',
        'neon-amber': '#FFB000',
        'neon-purple': '#BD00FF',
        'neon-green': '#00FF66',
        'neon-red': '#FF0055',
        'terminal-green': '#39FF14'
      },
      fontFamily: {
        mono: ['"JetBrains Mono"', 'monospace', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
        'code-display': ['"JetBrains Mono"', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      spacing: {
        xs: '4px',
        base: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '48px',
        gutter: '16px',
        margin: '20px',
      }
    },
  },
  plugins: [],
};
